version: 2.1
executors:
  node-postgres:
    docker:
      - image: circleci/node:8.14.0
        environment:
            DATABASE_URL: postgresql://root@localhost/circle_test
      - image: circleci/postgres:10-alpine-ram
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle_test
            POSTGRES_PASSWORD: ""
    working_directory: ~/repo
jobs:
  test:
    executor: node-postgres
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
workflows:
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
